pipeline{
    agent any
    options {
        // Timeout counter starts AFTER agent is allocated
        timeout(time: 1, unit: 'SECONDS')
    }
    environment{
        IMAGE_NAME='productpage'
        VERSION="v${env.BUILD_NUMBER}"
        REPO='bennyleder'
        CREDENTIALS_ID='myDHCred'
    }      
    stages {
        stage('Checkout') {
            steps {
               git 'https://github.com/bennyleder/devopshift-welcome.git'
            }
        }   

        stage('Build'){
            steps {
                script {
                sh 'docker build  --tag ${IMAGE_NAME}:${VERSION}-build -f welcome/app/bookinfo/src/productpage/Dockerfile welcome/app/bookinfo/src/productpage'
                }
            }
        }   
        stage('Test'){
            steps{
                script{
                    sh'docker build  --tag ${IMAGE_NAME}:${VERSION}-test -f welcome/app/bookinfo/src/productpage/Dockerfile welcome/app/bookinfo/src/productpage'
                    sh'docker run --rm ${IMAGE_NAME}:${VERSION}-test'}
                }
        }
        stage('Run'){
            steps{
                script{
                    sh'docker build  --tag ${IMAGE_NAME}:${VERSION} -f welcome/app/bookinfo/src/productpage/Dockerfile welcome/app/bookinfo/src/productpage'
                }
            }   
        }
    stage('Push'){
            steps{
                script{
                    docker.withRegistry('https://index.docker.io/v1/',"${CREDENTIALS_ID}") {
                        sh'''
                        docker push${REPO}/${IMAGE_NAME}:${VERSION}
                        docker tag ${REPO}/${IMAGE_NAME}:${VERSION} ${REPO}/${IMAGE_NAME}:latest
                        docker push ${REPO}/${IMAGE_NAME}:latest
                        '''

                    }
                }   
            }   
        }
    }
}